// Mocks generated by Mockito 5.0.9 from annotations
// in yerke_test_app/test/feature/main_screen/domain/usecases/fetch_art_objects_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yerke_test_app/core/api/exceptions.dart' as _i5;
import 'package:yerke_test_app/feature/main_screen/data/repositories/main_screen_repository_impl.dart'
    as _i3;
import 'package:yerke_test_app/feature/main_screen/domain/entities/art_object.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [MainScreenRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainScreenRepositoryImpl extends _i1.Mock
    implements _i3.MainScreenRepositoryImpl {
  MockMainScreenRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppExceptions, List<_i6.ArtObject>>> fetchArtModels(
          [int? currentPage = 1]) =>
      (super.noSuchMethod(Invocation.method(#fetchArtModels, [currentPage]),
          returnValue:
              Future<_i2.Either<_i5.AppExceptions, List<_i6.ArtObject>>>.value(
                  _FakeEither<_i5.AppExceptions, List<_i6.ArtObject>>())) as _i4
          .Future<_i2.Either<_i5.AppExceptions, List<_i6.ArtObject>>>);
}
