// Mocks generated by Mockito 5.0.9 from annotations
// in yerke_test_app/test/feature/main_screen/data/repositories/main_screen_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yerke_test_app/feature/main_screen/data/datasource/main_screen_remote_datasource.dart'
    as _i2;
import 'package:yerke_test_app/feature/main_screen/domain/entities/art_object.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MainScreenRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainScreenRemoteDatasource extends _i1.Mock
    implements _i2.MainScreenRemoteDatasource {
  MockMainScreenRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ArtObject>> fetchArtObjects([int? currentPage = 1]) =>
      (super.noSuchMethod(Invocation.method(#fetchArtObjects, [currentPage]),
              returnValue: Future<List<_i4.ArtObject>>.value(<_i4.ArtObject>[]))
          as _i3.Future<List<_i4.ArtObject>>);
}
